### ISSUE TITLE
Compatibility?

### ISSUE THREAD

**Issue by Alecyrus** [Darrenpan20/Matebook-X-Pro-Mojave-hackintosh-#1]
@Darrenpan20  Thanks for your awesome work. So I want to know something about the compatibility with macOS. WiFi work? Touch pad? Bluetooth? and 3000x2000 screen?

**Comment by Darrenpan20** [comment]
No WiFi, need an external card. Bluetooth works if restarted after starting the module from windows. Touchpad with 2,3 and 4 finger touch. However, tap and drag doesn’t work. You’ll need to click and drag. 3000x2000 screen is running with HiDPI and converted to 1500x1000.
